server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/accountsdb
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
