services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      start_period: 10s
      timeout: 5s
      interval: 10s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "rexxay/configserver"
    container_name: configserver-ms
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      timeout: 5s
      interval: 10s
      retries: 10
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  mysqldb:
    image: mysql
    container_name: mysql_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: network-deploy-service

  accounts:
    image: "rexxay/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      mysqldb:
        condition: service_healthy

  loans:
    image: "rexxay/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      mysqldb:
        condition: service_healthy

  cards:
    image: "rexxay/cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      mysqldb:
        condition: service_healthy

networks:
  eazybank:
    driver: "bridge"
