services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      start_period: 10s
      timeout: 5s
      interval: 10s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - eazybank

  configserver:
    image: "rexxay/configserver"
    container_name: configserver-ms
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      timeout: 5s
      interval: 10s
      retries: 10
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - eazybank

  accounts:
    image: "rexxay/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - eazybank

  loans:
    image: "rexxay/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - eazybank

  cards:
    image: "rexxay/cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - eazybank

networks:
  eazybank:
    driver: "bridge"
