server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: "git@github.com:Rijkstarhn/MiniBankConfig.git"
          default-label: master # branch tag
          timeout: 5 # 5 seconds
          clone-on-start: true # clone from the repo when start
          force-pull: true # to force usage of remote repo instead of local
#        native:
#          search-locations: "classpath:/config"
management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


