server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Rijkstarhn/MiniBankConfig.git"
          default-label: master # branch tag
          timeout: 5 # 5 seconds
          clone-on-start: true # clone from the repo when start
          force-pull: true # to force usage of remote repo instead of local
#        native:
#          search-locations: "classpath:/config"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"


